### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by cxmeronmcgregor** [codesidian/Python-MissionChiefBot#3]
Traceback (most recent call last):
  File "C:\Users\aircr\Documents\MissionChief Tool\missionchief_bot.py", line 1, in <module>
    from splinter import Browser
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\__init__.py", line 5, in <module>
    from splinter.browser import Browser  # NOQA
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\browser.py", line 9, in <module>
    from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\driver\webdriver\__init__.py", line 16, in <module>
    from six import BytesIO
ModuleNotFoundError: No module named 'six'

**Comment by codesidian** [comment]
I'm not surprised. It's old.

**Comment by codesidian** [comment]
Just updated it. You can try and use it now.

**Comment by cxmeronmcgregor** [comment]
Still does not work

Traceback (most recent call last):
  File "C:\Users\aircr\Documents\MissionChief Tool\22\Python-MissionChiefBot-master\missionchief_bot.py", line 1, in <module>
    from splinter import Browser
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\__init__.py", line 5, in <module>
    from splinter.browser import Browser  # NOQA
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\browser.py", line 9, in <module>
    from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
  File "C:\Users\aircr\AppData\Local\Programs\Python\Python37-32\lib\site-packages\splinter\driver\webdriver\__init__.py", line 16, in <module>
    from six import BytesIO
ModuleNotFoundError: No module named 'six'
>>>

**Comment by codesidian** [comment]
Did you follow :-
pip install splinter-

Go and grab the latest chromedriver from: 'http://chromedriver.chromium.org/'

Put that in the same directory at the python script.

Open account.txt and replace corresponding lines with your account information

run missionchief_bot.py

**Comment by Brandjuh** [comment]
Followed the steps, I get the same error.

**Comment by codesidian** [comment]
Are you running Python version 3.7?

**Comment by Brandjuh** [comment]
Yes
