### ISSUE TITLE
Fail to log in

### ISSUE THREAD

**Issue by Torilius** [codesidian/Python-MissionChiefBot#65]
---
name: Torilius
about: fails to login user with correct details from config.ini
title: 'Fails to log in'
labels: issue
assignees: codesidian, jackbayliss

---

**Describe the bug**
Fails to log in after opening the missionchief.com/signin page.

**Upload your debug.log file**
Nothng in debug.log 

**To Reproduce**
1. Go to 'Python-MissionChiefBot-master'
2. Open 'run.bat'
3. 

**Expected behavior**

**Screenshots**

Connecting to the region:  United States

logging in
Traceback (most recent call last):
  File "C:\Users\MYNAME\Desktop\Freebot\Python-MissionChiefBot-master\botfiles\missionchief_bot.py", line 505, in <module>
    begin()
  File "C:\Users\MYNAME\Desktop\Freebot\Python-MissionChiefBot-master\botfiles\missionchief_bot.py", line 501, in begin
    MissonChiefBot()
  File "C:\Users\MYNAME\Desktop\Freebot\Python-MissionChiefBot-master\botfiles\missionchief_bot.py", line 49, in __init__
    logged_in = login(username,password,browser)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MYNAME\Desktop\Freebot\Python-MissionChiefBot-master\botfiles\missionchief_bot.py", line 397, in login
    user =  browser.find_element_by_id('user_email')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [Chrome]
 - Version [Google Chrome - Version 109.0.5414.75 (Official Build) (64-bit)]

**Additional context**

Really just want to be able to clear the transports. as well as complete the tiny calls. Speed is not an issue.

**Comment by jackbayliss** [comment]
@Torilius  Code base is not updated,  it's due to the following [deprecation](https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el)

You'll need to update the code.
