### ISSUE TITLE
Same issue in different servers

### ISSUE THREAD

**Issue by raytrax** [codesidian/Python-MissionChiefBot#7]
I try it in centos6 and centos7, with python, python2, python34 and python37....
Same error all times:

Traceback (most recent call last):
  File "missionchief_bot.py", line 60, in <module>
    browser = Browser('chrome', **executable_path)
  File "/usr/local/lib/python3.7/site-packages/splinter/browser.py", line 64, in Browser
    return driver(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/splinter/driver/webdriver/chrome.py", line 43, in __init__
    self.driver = Chrome(options=options, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './chromedriver.exe'

Any help will be useful, thank you!

**Comment by codesidian** [comment]
OSError: [Errno 8] Exec format error: './**chromedriver.exe**'

Try windows bud.

**Comment by raytrax** [comment]
¿Bud?
Nowhere do you indicate that this only works on windows...

Edit1. Ready and working over windows, it is important to know the SO as that chrome should be used.

**Comment by codesidian** [comment]
OK.
